/**
 * Represents the possible statuses of the application during its lifecycle.
 */
export type AppStatus = 'idle' | 'parsing' | 'ready' | 'loading' | 'success' | 'error';

/**
 * Represents the selected difficulty filter for questions. 'All' means no filter.
 */
export type DifficultyFilter = QuestionDifficulty | 'All';

/**
 * Represents the main state of the application.
 */
export interface AppState {
  /** The current operational status of the app. */
  status: AppStatus;
  /** The extracted text content from the uploaded resume. */
  resumeText: string | null;
  /** The name of the uploaded file. */
  fileName: string | null;
  /** The list of generated interview questions. */
  questions: InterviewQuestion[];
  /** An error message, if any error has occurred. */
  error: string | null;
  /** The currently active difficulty filter. */
  difficultyFilter: DifficultyFilter;
}

/**
 * Enum for the difficulty levels of interview questions.
 */
export enum QuestionDifficulty {
  Easy = 'Easy',
  Medium = 'Medium',
  Hard = 'Hard'
}

/**
 * Represents a single interview question generated by the AI.
 */
export interface InterviewQuestion {
  /** The question text. */
  question: string;
  /** A guideline for how to answer the question, from the candidate's perspective. */
  answer_guideline: string;
  /** The category the question belongs to (e.g., "Technical", "Behavioral"). */
  category: string;
  /** The difficulty level of the question. */
  difficulty: QuestionDifficulty;
}

/**
 * Represents a single message in the chat history.
 */
export interface ChatMessage {
  /** The author of the message. */
  role: 'user' | 'model';
  /** The text content of the message. */
  text: string;
}
